services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      POSTGRES_DB: yourtube
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  app:
    image: cosmtrek/air
    depends_on:
      - db
    working_dir: /app
    volumes:
      - ../:/app
      - $GOPATH/pkg/mod:/go/pkg/mod
    ports:
      - "8080:8090"
    environment:
      POSTGRES_DSN: postgresql://postgres:password@db:5432/yourtube?sslmode=disable
